# site
title: 两片
description: 我宁可喝毒药！我从没喝过酒！
keywords:
rss: rss.xml
favicon: icon.png

# site url. you can set as 'http://yoursite.com/child' if need
# please add 'http://' or 'https://'
url: https://enzo-yang.github.io

# comment
disqus: enzo-yang

# language
language: en

# theme
theme: donob

# pagination
# set 0 if no need paging
per_page: 10
archives_per_page: 30

# thumbnail mode
# 1: use the first image as thumbnail and remove the image
# 2: use the first image as thumbnail but not remove the image
thumbnail_mode: 2

#menu
menu:
  Archives: /archives/
  About: /about/

# category
default_category: blog

# html output directory or child directory e.g. 'child'
public_dir: public

# category directory
category_dir:

# tag directory
tag_dir:

# post directory
post_dir:

# archives directory
archives_dir:

# source
# site content source
# your github username/repository
user: enzo-yang
repository: enzo-yang.github.io

# site post authors filter
authors:
  - enzo-yang
#  - author0
#  - author1

# GitHub access token(optional)
# token should be separated by '#' if you push this file to GitHub
token: 4#cbf4db4db9df7de7be326c788aae1ae73202c16

# json output
# boolean or string
# you can set json output path
json: false

# dev mode
dev: false

# other
# customize some settings if you need

# duoshuo:
# blogroll:
#  GitHub: https://github.com
